-- Drop all tables and relationships
DROP TABLE IF EXISTS university.schedule_student CASCADE;
DROP TABLE IF EXISTS university.course_student CASCADE;
DROP TABLE IF EXISTS university.course_teacher CASCADE;
DROP TABLE IF EXISTS university.schedules CASCADE;
DROP TABLE IF EXISTS university.users CASCADE;
DROP TABLE IF EXISTS university.roles CASCADE;
DROP TABLE IF EXISTS university.user_roles CASCADE;
DROP TABLE IF EXISTS university.groups CASCADE;
DROP TABLE IF EXISTS university.lesson_types CASCADE;
DROP TABLE IF EXISTS university.persons CASCADE;
DROP TABLE IF EXISTS university.courses CASCADE;
DROP TABLE IF EXISTS university.classrooms CASCADE;

-- Drop sequences if necessary
DROP SEQUENCE IF EXISTS university.classrooms_classroom_id_seq CASCADE;
DROP SEQUENCE IF EXISTS university.courses_course_id_seq CASCADE;
DROP SEQUENCE IF EXISTS university.groups_group_id_seq CASCADE;
DROP SEQUENCE IF EXISTS university.lesson_types_lesson_type_id_seq CASCADE;
DROP SEQUENCE IF EXISTS university.persons_person_id_seq CASCADE;
DROP SEQUENCE IF EXISTS university.roles_role_id_seq CASCADE;
DROP SEQUENCE IF EXISTS university.schedules_schedule_id_seq CASCADE;
DROP SEQUENCE IF EXISTS university.users_user_id_seq CASCADE;

-- Create schema
CREATE SCHEMA IF NOT EXISTS university AUTHORIZATION university_database;

-- Create tables and sequences
CREATE TABLE IF NOT EXISTS university.classrooms (
    floor integer,
    classroom_id bigint NOT NULL,
    number character varying(255)
);
ALTER TABLE university.classrooms OWNER TO university_database;
ALTER TABLE university.classrooms ALTER COLUMN classroom_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME university.classrooms_classroom_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS university.course_student (
    course_id bigint NOT NULL,
    student_id bigint NOT NULL
);
ALTER TABLE university.course_student OWNER TO university_database;

CREATE TABLE IF NOT EXISTS university.course_teacher (
    course_id bigint NOT NULL,
    teacher_id bigint NOT NULL
);
ALTER TABLE university.course_teacher OWNER TO university_database;

CREATE TABLE IF NOT EXISTS university.courses (
    course_id bigint NOT NULL,
    course_description character varying(255),
    course_name character varying(255)
);
ALTER TABLE university.courses OWNER TO university_database;
ALTER TABLE university.courses ALTER COLUMN course_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME university.courses_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS university.groups (
    group_id bigint NOT NULL,
    group_name character varying(255)
);
ALTER TABLE university.groups OWNER TO university_database;
ALTER TABLE university.groups ALTER COLUMN group_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME university.groups_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS university.lesson_types (
    rated boolean,
    lesson_type_id bigint NOT NULL,
    name character varying(255)
);
ALTER TABLE university.lesson_types OWNER TO university_database;
ALTER TABLE university.lesson_types ALTER COLUMN lesson_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME university.lesson_types_lesson_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS university.persons (
    date_of_birth date,
    person_id bigint NOT NULL,
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    phone_number character varying(255)
);
ALTER TABLE university.persons OWNER TO university_database;
ALTER TABLE university.persons ALTER COLUMN person_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME university.persons_person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS university.roles (
    role_id bigint NOT NULL,
    description character varying(255),
    name character varying(255)
);
ALTER TABLE university.roles OWNER TO university_database;
ALTER TABLE university.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME university.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS university.schedule_student (
    schedule_id bigint NOT NULL,
    student_id bigint NOT NULL
);
ALTER TABLE university.schedule_student OWNER TO university_database;

CREATE TABLE IF NOT EXISTS university.schedules (
    classroom_id bigint NOT NULL,
    course_id bigint NOT NULL,
    lesson_end timestamp(6) without time zone NOT NULL,
    lesson_start timestamp(6) without time zone NOT NULL,
    lesson_type_id bigint NOT NULL,
    schedule_id bigint NOT NULL,
    teacher_id bigint NOT NULL
);
ALTER TABLE university.schedules OWNER TO university_database;
ALTER TABLE university.schedules ALTER COLUMN schedule_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME university.schedules_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS university.user_roles (
    role_id bigint NOT NULL,
    user_id bigint NOT NULL
);
ALTER TABLE university.user_roles OWNER TO university_database;

CREATE TABLE IF NOT EXISTS university.users (
    enabled boolean,
    group_id bigint,
    person_id bigint,
    user_id bigint NOT NULL,
    dtype character varying(31) NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);
ALTER TABLE university.users OWNER TO university_database;
ALTER TABLE university.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME university.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY university.classrooms
    ADD CONSTRAINT classrooms_pkey PRIMARY KEY (classroom_id);

ALTER TABLE ONLY university.course_student
    ADD CONSTRAINT course_student_pkey PRIMARY KEY (course_id, student_id);

ALTER TABLE ONLY university.course_teacher
    ADD CONSTRAINT course_teacher_pkey PRIMARY KEY (course_id, teacher_id);

ALTER TABLE ONLY university.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (course_id);

ALTER TABLE ONLY university.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (group_id);

ALTER TABLE ONLY university.lesson_types
    ADD CONSTRAINT lesson_types_pkey PRIMARY KEY (lesson_type_id);

ALTER TABLE ONLY university.persons
    ADD CONSTRAINT persons_pkey PRIMARY KEY (person_id);

ALTER TABLE ONLY university.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);

ALTER TABLE ONLY university.schedule_student
    ADD CONSTRAINT schedule_student_pkey PRIMARY KEY (schedule_id, student_id);

ALTER TABLE ONLY university.schedules
    ADD CONSTRAINT schedules_pkey PRIMARY KEY (schedule_id);

ALTER TABLE ONLY university.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (role_id, user_id);

ALTER TABLE ONLY university.users
    ADD CONSTRAINT users_person_id_key UNIQUE (person_id);

ALTER TABLE ONLY university.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY university.users
    ADD CONSTRAINT users_username_key UNIQUE (username);

ALTER TABLE ONLY university.schedule_student
    ADD CONSTRAINT fk63ejcp2a0myrr7g7xi35siu15 FOREIGN KEY (student_id) REFERENCES university.users(user_id);

ALTER TABLE ONLY university.course_student
    ADD CONSTRAINT fk7735e1tmooufb4suulr267012 FOREIGN KEY (student_id) REFERENCES university.users(user_id);

ALTER TABLE ONLY university.schedules
    ADD CONSTRAINT fk8lk7tc6810l6pgy077cavr8uq FOREIGN KEY (course_id) REFERENCES university.courses(course_id);

ALTER TABLE ONLY university.schedule_student
    ADD CONSTRAINT fkdgbcrj4gyf3f2bjfb6bqrhmxh FOREIGN KEY (schedule_id) REFERENCES university.schedules(schedule_id);

ALTER TABLE ONLY university.users
    ADD CONSTRAINT fkemfuglprp85bh5xwhfm898ysc FOREIGN KEY (group_id) REFERENCES university.groups(group_id);

ALTER TABLE ONLY university.schedules
    ADD CONSTRAINT fketjivfiadf6tro4vbyxhn52cg FOREIGN KEY (classroom_id) REFERENCES university.classrooms(classroom_id);

ALTER TABLE ONLY university.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES university.roles(role_id);

ALTER TABLE ONLY university.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES university.users(user_id);

ALTER TABLE ONLY university.course_teacher
    ADD CONSTRAINT fkiq1y5ig0ahflkvmcowpj8btr FOREIGN KEY (teacher_id) REFERENCES university.users(user_id);

ALTER TABLE ONLY university.schedules
    ADD CONSTRAINT fkk3l6clk2nk64svalyk2lw03pq FOREIGN KEY (teacher_id) REFERENCES university.users(user_id);

ALTER TABLE ONLY university.course_student
    ADD CONSTRAINT fklmsbddqkv96q4nijkrxuof3ug FOREIGN KEY (course_id) REFERENCES university.courses(course_id);

ALTER TABLE ONLY university.users
    ADD CONSTRAINT fkmvbq8q4vpi6csivw9wcnq6ho5 FOREIGN KEY (person_id) REFERENCES university.persons(person_id);

ALTER TABLE ONLY university.course_teacher
    ADD CONSTRAINT fknlcjwe2dijg0uhd6wyp9plf1f FOREIGN KEY (course_id) REFERENCES university.courses(course_id);

ALTER TABLE ONLY university.schedules
    ADD CONSTRAINT fkobqt89pp2ilnh9dkgcrq47pj1 FOREIGN KEY (lesson_type_id) REFERENCES university.lesson_types(lesson_type_id);
